
VERSION = "13"

#############
## BUTTONS ##
#############
BUTTONS = {
    "CONTEXT": {
        "btReality":    "0",
        "btExercise":   "1",
        "btSimulation": "2"
    },
    "AFFILIATION": {
        "btPending":       "0",
        "btUnknown":       "1",
        "btAssumedFriend": "2",
        "btFriend":        "3",
        "btNeutral":       "4",
        "btSuspectJoker":  "5",
        "btHostileFaker":  "6"
    },
    "STATUS": {
        "btPresent":        "0",
        "btPlanned":        "1",
        "btFullyCapable":   "2",
        "btDamaged":        "3",
        "btDestroyed":      "4",
        "btFullToCapacity": "5"
    },
    "REINFORCED_REDUCED": {
        "btNotApplicableReinReduc": "",
        "btReinforced":             "(+)",
        "btReduced":                "(-)",
        "btReinforcedReduced":      "(±)"
    },
    "STACK": {
        "btStack1": 0,
        "btStack2": 1,
        "btStack3": 2,
        "btStack4": 3,
        "btStack5": 4,
        "btStack6": 5
    },
    "COLOR": {
        "btNoFill": "false",
        "btLight":  "Light",
        "btMedium": "Medium",
        "btDark":   "Dark",
        "btCustom": "Custom"
    },
    "ENGAGEMENT": {
        "btTarget": "TARGET",
        "btNonTarget": "NON-TARGET",
        "btExpired": "EXPIRED"
    },
    "SIGNATURE": {
        "btNotApplicableSignature": "",
        "btElectronicSignature":    "!"
    }
}

###############
## LISTBOXES ##
###############
SYMBOL_DETAILS = {
    "AIR": {
        "MainIcon": [
            {"label": "Unspecified", "value": "000000"},
            {"label": "Fixed Wing  –  Military", "value": "110100"},
            {"label": "Medical Evacuation (MEDEVAC)  –  Military Fixed Wing", "value": "110101"},
            {"label": "Attack/Strike  –  Military Fixed Wing", "value": "110102"},
            {"label": "Bomber  –  Military Fixed Wing", "value": "110103"},
            {"label": "Fighter  –  Military Fixed Wing", "value": "110104"},
            {"label": "Fighter/Bomber  –  Military Fixed Wing", "value": "110105"},
            {"label": "Cargo  –  Military Fixed Wing", "value": "110107"},
            {"label": "Electronic Combat (EC)/Jammer  –  Military Fixed Wing", "value": "110108"},
            {"label": "Tanker  –  Military Fixed Wing", "value": "110109"},
            {"label": "Patrol  –  Military Fixed Wing", "value": "110110"},
            {"label": "Reconnaissance  –  Military Fixed Wing", "value": "110111"},
            {"label": "Trainer  –  Military Fixed Wing", "value": "110112"},
            {"label": "Utility  –  Military Fixed Wing", "value": "110113"},
            {"label": "Vertical or Short Take-off and Landing (VSTOL)  –  Military Fixed Wing", "value": "110114"},
            {"label": "Airborne Command Post (ACP)  –  Military Fixed Wing", "value": "110115"},
            {"label": "Airborne Early Warning (AEW)  –  Military Fixed Wing", "value": "110116"},
            {"label": "Antisurface Warfare  –  Military Fixed Wing", "value": "110117"},
            {"label": "Antisubmarine Warfare  –  Military Fixed Wing", "value": "110118"},
            {"label": "Communications  –  Military Fixed Wing", "value": "110119"},
            {"label": "Combat Search and Rescue (CSAR)  –  Military Fixed Wing", "value": "110120"},
            {"label": "Electronic Support (ES)  –  Military Fixed Wing", "value": "110121"},
            {"label": "Government  –  Military Fixed Wing", "value": "110122"},
            {"label": "Mine Countermeasures (MCM)  –  Military Fixed Wing", "value": "110123"},
            {"label": "Personnel Recovery  –  Military Fixed Wing", "value": "110124"},
            {"label": "Search and Rescue  –  Military Fixed Wing", "value": "110125"},
            {"label": "Special Operations Forces  –  Military Fixed Wing", "value": "110126"},
            {"label": "Ultra Light  –  Military Fixed Wing", "value": "110127"},
            {"label": "Photographic Reconnaissance  –  Military Fixed Wing", "value": "110128"},
            {"label": "Very Important Person (VIP)  –  Military Fixed Wing", "value": "110129"},
            {"label": "Suppression of Enemy Air Defense  –  Military Fixed Wing", "value": "110130"},
            {"label": "Passenger  –  Military Fixed Wing", "value": "110131"},
            {"label": "Escort  –  Military Fixed Wing", "value": "110132"},
            {"label": "Electronic Attack (EA)  –  Military Fixed Wing", "value": "110133"},
            {"label": "Rotary Wing  –  Military", "value": "110200"},
            {"label": "Unmanned Aircraft (UA) / UAV / UAS / RPV – Military", "value": "110300"},
            {"label": "Vertical-Takeoff UAV (VT-UAV)  –  Military", "value": "110400"},
            {"label": "Lighter Than Air  –  Military", "value": "110500"},
            {"label": "Airship  –  Military", "value": "110600"},
            {"label": "Tethered Lighter than Air  –  Military", "value": "110700"},
            {"label": "Fixed Wing  –  Civilian", "value": "120100"},
            {"label": "Rotary Wing  –  Civilian", "value": "120200"},
            {"label": "Unmanned Aircraft (UA) / UAV / UAS / RPV  – Civilian", "value": "120300"},
            {"label": "Lighter Than Air  –  Civilian", "value": "120400"},
            {"label": "Airship  –  Civilian", "value": "120500"},
            {"label": "Tethered Lighter than Air  –  Civilian", "value": "120600"},
            {"label": "Medical Evacuation (MEDEVAC)  –  Civilian", "value": "120700"},
            {"label": "Bomb  –  Weapon", "value": "130100"},
            {"label": "Decoy  –  Weapon", "value": "130200"},
            {"label": "Manual Track  –  Manual Track", "value": "140000"}
        ],
        "FirstIconModifier": [
            {"label": "Unspecified", "value": "000"},
            {"label": "Government  –  Aircraft Type", "value": "013"},
            {"label": "Passenger  –  Aircraft Type", "value": "009"},
            {"label": "Tanker  –  Aircraft Type", "value": "006"},
            {"label": "Ultra Light  –  Aircraft Type", "value": "010"},
            {"label": "Armored  –  Capability", "value": "107"},
            {"label": "Attack or Attack/Strike  –  Capability", "value": "106"},
            {"label": "Ballistic Missile/Ballistic Missile Defense Shooter  –  Capability", "value": "108"},
            {"label": "Bridge/Bridging  –  Capability", "value": "109"},
            {"label": "Cargo  –  Capability", "value": "110"},
            {"label": "Close Protection  –  Capability", "value": "120"},
            {"label": "Combat  –  Capability", "value": "121"},
            {"label": "Command and Control  –  Capability", "value": "122"},
            {"label": "Command Post Node  –  Capability", "value": "116"},
            {"label": "Crowd and Riot Control  –  Capability", "value": "123"},
            {"label": "Cyberspace  –  Capability", "value": "115"},
            {"label": "Directed Energy  –  Capability", "value": "164"},
            {"label": "Electromagnetic  –  Capability", "value": "166"},
            {"label": "Explosive Ordnance Disposal  –  Capability", "value": "124"},
            {"label": "Guided Missile  –  Capability", "value": "133"},
            {"label": "Heavy  –  Capability", "value": "114"},
            {"label": "Intelligence Surveillance Reconnaissance  –  Capability", "value": "125"},
            {"label": "Joint Network Node  –  Capability", "value": "117"},
            {"label": "Light  –  Capability", "value": "112"},
            {"label": "Maintenance  –  Capability", "value": "126"},
            {"label": "Medevac/Medic/Medical  –  Capability", "value": "127"},
            {"label": "Medium  –  Capability", "value": "113"},
            {"label": "Other Guided Missile  –  Capability", "value": "134"},
            {"label": "Petroleum/POL  –  Capability", "value": "135"},
            {"label": "Retransmission Site  –  Capability", "value": "118"},
            {"label": "Search and Rescue  –  Capability", "value": "128"},
            {"label": "Security  –  Capability", "value": "129"},
            {"label": "Sniper  –  Capability", "value": "130"},
            {"label": "Special Operations Forces  –  Capability", "value": "131"},
            {"label": "Special Weapons and Tactics (SWAT)  –  Capability", "value": "132"},
            {"label": "Utility  –  Capability", "value": "111"},
            {"label": "Water  –  Capability", "value": "136"},
            {"label": "Weapon or Weapons  –  Capability", "value": "137"},
            {"label": "Biological  –  CBRN", "value": "139"},
            {"label": "Chemical  –  CBRN", "value": "138"},
            {"label": "Decontamination  –  CBRN", "value": "142"},
            {"label": "Nuclear  –  CBRN", "value": "141"},
            {"label": "Radiological  –  CBRN", "value": "140"},
            {"label": "Accident  –  Composite Loss or Incident Qualifier", "value": "145"},
            {"label": "Assassination  –  Crime", "value": "146"},
            {"label": "Execution  –  Crime", "value": "147"},
            {"label": "Hijacker  –  Crime", "value": "165"},
            {"label": "Kidnapping  –  Crime", "value": "148"},
            {"label": "Piracy  –  Crime", "value": "149"},
            {"label": "Rape  –  Crime", "value": "150"},
            {"label": "Airborne Command Post (ACP)  –  Military Aircraft Type", "value": "011"},
            {"label": "Airborne Early Warning (AEW)  –  Military Aircraft Type", "value": "012"},
            {"label": "Bomber  –  Military Aircraft Type", "value": "002"},
            {"label": "Fighter  –  Military Aircraft Type", "value": "004"},
            {"label": "Fighter/Bomber  –  Military Aircraft Type", "value": "033"},
            {"label": "Interceptor  –  Military Aircraft Type", "value": "005"},
            {"label": "Antisurface Warfare  –  Military Mission Area", "value": "032"},
            {"label": "Combat Search and Rescue (CSAR)  –  Military Mission Area", "value": "030"},
            {"label": "Electronic Attack (EA)  –  Military Mission Area", "value": "035"},
            {"label": "Electronic Combat (EC)/Jammer  –  Military Mission Area", "value": "016"},
            {"label": "Electronic Support (ES)  –  Military Mission Area", "value": "024"},
            {"label": "Suppression of Enemy Air Defenses  –  Military Mission Area", "value": "031"},
            {"label": "Antisubmarine Warfare  –  Mission Area", "value": "151"},
            {"label": "ASW Helo- LAMPS  –  Mission Area", "value": "038"},
            {"label": "ASW Helo- SH-60R  –  Mission Area", "value": "039"},
            {"label": "Communications  –  Mission Area", "value": "023"},
            {"label": "Escort  –  Mission Area", "value": "152"},
            {"label": "Intensive Care  –  Mission Area", "value": "034"},
            {"label": "Mine Countermeasures  –  Mission Area", "value": "153"},
            {"label": "Mine WarfareAPP-06 uses ‘MW’  –  Mission Area", "value": "154"},
            {"label": "Multi-Mission  –  Mission Area", "value": "036"},
            {"label": "Patrol  –  Mission Area", "value": "017"},
            {"label": "Personnel Recovery  –  Mission Area", "value": "021"},
            {"label": "Photographic (Reconnaissance)  –  Mission Area", "value": "20"},
            {"label": "Reconnaissance  –  Mission Area", "value": "018"},
            {"label": "Surface Warfare  –  Mission Area", "value": "155"},
            {"label": "Trainer  –  Mission Area", "value": "019"},
            {"label": "Very Important Person (VIP) Transport  –  Mission Area", "value": "029"},
            {"label": "Fixed WingNot used by USAF  –  Mobility", "value": "102"},
            {"label": "Robotic  –  Mobility", "value": "101"},
            {"label": "Rotary Wing  –  Mobility", "value": "103"},
            {"label": "Tilt-Rotor  –  Mobility", "value": "104"},
            {"label": "Unmanned Aircraft (UA)/ UAV / UAS / RPV  –  Mobility", "value": "100"},
            {"label": "VSTOL/VTOL or Helicopter Equipped  –  Mobility", "value": "105"},
            {"label": "OrganizationCivilian  –  Organization", "value": "143"},
            {"label": "Government Organization / Government Organization Member – Organization", "value": "144"},
            {"label": "Battalion  –  Support Level", "value": "163"},
            {"label": "Brigade  –  Support Level", "value": "119"},
            {"label": "Command  –  Support Level", "value": "156"},
            {"label": "Company  –  Support Level", "value": "157"},
            {"label": "Platoon/Detachment  –  Support Level", "value": "158"},
            {"label": "Regiment Group  –  Support Level", "value": "159"},
            {"label": "Section  –  Support Level", "value": "160"},
            {"label": "Squad  –  Support Level", "value": "161"},
            {"label": "Team/Crew  –  Support Level", "value": "162"}
        ],
        "SecondIconModifier": [
            {"label": "Unspecified", "value": "000"},
            {"label": "Autonomous Control  –  Capability", "value": "110"},
            {"label": "Close Range  –  Capability", "value": "117"},
            {"label": "Cyberspace  –  Capability", "value": "122"},
            {"label": "Expendable  –  Capability", "value": "112"},
            {"label": "Heavy  –  Capability", "value": "118"},
            {"label": "Light  –  Capability", "value": "121"},
            {"label": "Light and Medium  –  Capability", "value": "120"},
            {"label": "Long Range  –  Capability", "value": "114"},
            {"label": "Medical Bed  –  Capability", "value": "124"},
            {"label": "Medium  –  Capability", "value": "119"},
            {"label": "Medium Range  –  Capability", "value": "115"},
            {"label": "Mountain  –  Capability", "value": "113"},
            {"label": "Multifunctional  –  Capability", "value": "125"},
            {"label": "Railroad/Railway  –  Capability", "value": "102"},
            {"label": "Remotely Piloted  –  Capability", "value": "111"},
            {"label": "Security Force Assistance  –  Capability", "value": "123"},
            {"label": "Short Range  –  Capability", "value": "116"},
            {"label": "Airborne  –  Mobility", "value": "100"},
            {"label": "Bicycle Equipped  –  Mobility", "value": "101"},
            {"label": "Fixed Wing  –  Mobility", "value": "107"},
            {"label": "Robotic  –  Mobility", "value": "109"},
            {"label": "Rotary Wing  –  Mobility", "value": "108"},
            {"label": "Ski  –  Mobility", "value": "103"},
            {"label": "Tracked  –  Mobility", "value": "104"},
            {"label": "Wheeled (Limited Cross Country)  –  Mobility", "value": "105"},
            {"label": "Wheeled X (Cross Country)  –  Mobility", "value": "106"},
            {"label": "Boom and Drogue  –  Re-Fueling Capability(Used with tanker only)", "value": "006"},
            {"label": "Boom–Only  –  Re-Fueling Capability(Used with tanker only)", "value": "004"},
            {"label": "Drogue–Only  –  Re-Fueling Capability(Used with tanker only)", "value": "005"},
            {"label": "Downlinked  –  Track Link Availability", "value": "011"}
        ],
        "EchelonMobility": [
            {"label": "Not Applicable", "value": "00"}
        ],
        "HeadquartersTaskforceDummy": [
            {"label": "Unspecified", "value": "0"},
            {"label": "Feint / Dummy", "value": "1"},
            {"label": "Headquarters", "value": "2"},
            {"label": "Feint / Dummy Headquarters", "value": "3"},
            {"label": "Task Force", "value": "4"},
            {"label": "Feint / Dummy Task Force", "value": "5"},
            {"label": "Task Force Headquarters", "value": "6"},
            {"label": "Feint / Dummy Task Force Headquarters", "value": "7"}
        ]
    },
    
    "AIR_MISSILE": {
        "MainIcon": [
            {"label": "Missile", "value": "110000"}
        ],
        "FirstIconModifier": [
            {"label": "Unspecified", "value": "000"},
            {"label": "Air  –  Launch Origin", "value": "001"},
            {"label": "Space  –  Launch Origin", "value": "004"},
            {"label": "Subsurface  –  Launch Origin", "value": "003"},
            {"label": "Surface  –  Launch Origin", "value": "002"},
            {"label": "Anti-Ballistic  –  Missile Class", "value": "005"},
            {"label": "Ballistic  –  Missile Class", "value": "006"},
            {"label": "Cruise  –  Missile Class", "value": "007"},
            {"label": "Hypersonic  –  Missile Class", "value": "009"},
            {"label": "Interceptor  –  Missile Class", "value": "008"}
        ],
        "SecondIconModifier": [
            {"label": "Unspecified", "value": "000"},
            {"label": "Autonomous Control  –  Capability", "value": "110"},
            {"label": "Close Range  –  Capability", "value": "117"},
            {"label": "Cyberspace  –  Capability", "value": "122"},
            {"label": "Expendable  –  Capability", "value": "112"},
            {"label": "Heavy  –  Capability", "value": "118"},
            {"label": "Light  –  Capability", "value": "121"},
            {"label": "Light and Medium  –  Capability", "value": "120"},
            {"label": "Long Range  –  Capability", "value": "114"},
            {"label": "Medical Bed  –  Capability", "value": "124"},
            {"label": "Medium  –  Capability", "value": "119"},
            {"label": "Medium Range  –  Capability", "value": "115"},
            {"label": "Mountain  –  Capability", "value": "113"},
            {"label": "Multifunctional  –  Capability", "value": "125"},
            {"label": "Railroad/Railway  –  Capability", "value": "102"},
            {"label": "Remotely Piloted  –  Capability", "value": "111"},
            {"label": "Security Force Assistance  –  Capability", "value": "123"},
            {"label": "Short Range  –  Capability", "value": "116"},
            {"label": "Air  –  Missile Destination", "value": "001"},
            {"label": "Space  –  Missile Destination", "value": "004"},
            {"label": "Subsurface  –  Missile Destination", "value": "003"},
            {"label": "Surface  –  Missile Destination", "value": "002"},
            {"label": "Intercontinental  –  Missile Range (5500km or greater)", "value": "016"},
            {"label": "Intermediate Range  –  Missile Range (1000km to 3500km - Typically used in reference to ballistic missile)", "value": "014"},
            {"label": "Long Range  –  Missile Range (3500km to 5500km)", "value": "015"},
            {"label": "Medium Range  –  Missile Range (1000km to 3500km - Typically used in reference to surface-to-air missile)", "value": "013"},
            {"label": "Short Range  –  Missile Range (1000km or less)", "value": "012"},
            {"label": "Launched  –  Missile Status", "value": "005"},
            {"label": "Evolved Sea Sparrow Missile (ESSM)  –  Missile Type-AAW (Used with INTERCEPTOR modifier 1 only)", "value": "010"},
            {"label": "Rolling Airframe Missile (RAM)  –  Missile Type-AAW. (Used with INTERCEPTOR modifier 1 only)", "value": "011"},
            {"label": "Standard Missile-2 (SM-2)  –  Missile Type-AAW (Used with INTERCEPTOR modifier 1 only)", "value": "008"},
            {"label": "Standard Missile-6 (SM-6)  –  Missile Type-AAW (Used with INTERCEPTOR modifier 1 only)", "value": "009"},
            {"label": "Patriot  –  Missile Type-BMD (Used with INTERCEPTOR modifier 1 only)", "value": "007"},
            {"label": "Airborne  –  Mobility", "value": "100"},
            {"label": "Bicycle Equipped  –  Mobility", "value": "101"},
            {"label": "Fixed Wing  –  Mobility", "value": "107"},
            {"label": "Robotic  –  Mobility", "value": "109"},
            {"label": "Rotary Wing  –  Mobility", "value": "108"},
            {"label": "Ski  –  Mobility", "value": "103"},
            {"label": "Tracked  –  Mobility", "value": "104"},
            {"label": "Wheeled (Limited Cross Country)  –  Mobility", "value": "105"},
            {"label": "Wheeled X (Cross Country)  –  Mobility", "value": "106"}
        ],
        "EchelonMobility": [
            {"label": "Not Applicable", "value": "00"}
        ],
        "HeadquartersTaskforceDummy": [
            {"label": "Unspecified", "value": "0"},
            {"label": "Feint / Dummy", "value": "1"},
            {"label": "Headquarters", "value": "2"},
            {"label": "Feint / Dummy Headquarters", "value": "3"},
            {"label": "Task Force", "value": "4"},
            {"label": "Feint / Dummy Task Force", "value": "5"},
            {"label": "Task Force Headquarters", "value": "6"},
            {"label": "Feint / Dummy Task Force Headquarters", "value": "7"}
        ]
    },
    
    "SPACE":{
        "MainIcon": [
            {"label": "Unspecified", "value": "0000"},
            {"label": "Military", "value": "0000"},
            {"label": "Space Vehicle  –  Military", "value": "0000"},
            {"label": "Re-Entry Vehicle  –  Military", "value": "0000"},
            {"label": "Planet Lander  –  Military", "value": "0000"},
            {"label": "Orbiter Shuttle  –  Military", "value": "0000"},
            {"label": "Capsule  –  Military", "value": "0000"},
            {"label": "Satellite, General  –  Military", "value": "0000"},
            {"label": "Satellite  –  Military", "value": "0000"},
            {"label": "Antisatellite Weapon  –  Military", "value": "0000"},
            {"label": "Astronomical Satellite  –  Military", "value": "0000"},
            {"label": "Biosatellite  –  Military", "value": "0000"},
            {"label": "Communications Satellite  –  Military", "value": "0000"},
            {"label": "Earth Observation Satellite  –  Military", "value": "0000"},
            {"label": "Miniaturized Satellite  –  Military", "value": "0000"},
            {"label": "Navigational Satellite  –  Military", "value": "0000"},
            {"label": "Reconnaissance Satellite  –  Military", "value": "0000"},
            {"label": "Space Station  –  Military", "value": "0000"},
            {"label": "Tethered Satellite  –  Military", "value": "0000"},
            {"label": "Weather Satellite  –  Military", "value": "0000"},
            {"label": "Space Launched Vehicle (SLV)  –  Military", "value": "0000"},
            {"label": "Orbiter Shuttle  –  Civilian", "value": "0000"},
            {"label": "Capsule  –  Civilian", "value": "0000"},
            {"label": "Satellite  –  Civilian", "value": "0000"},
            {"label": "Astronomical Satellite  –  Civilian", "value": "0000"},
            {"label": "Biosatellite  –  Civilian", "value": "0000"},
            {"label": "Communications Satellite  –  Civilian", "value": "0000"},
            {"label": "Earth Observation Satellite  –  Civilian", "value": "0000"},
            {"label": "Miniaturized Satellite  –  Civilian", "value": "0000"},
            {"label": "Navigational Satellite  –  Civilian", "value": "0000"},
            {"label": "Space Station  –  Civilian", "value": "0000"},
            {"label": "Tethered Satellite  –  Civilian", "value": "0000"},
            {"label": "Weather Satellite  –  Civilian", "value": "0000"},
            {"label": "Planetary Lander  –  Civilian", "value": "0000"},
            {"label": "Space Vehicle  –  Civilian", "value": "0000"},
            {"label": "Manual Track", "value": "0000"}
        ],
        "FirstIconModifier": [
            {"label": "Unspecified", "value": "00"},
            {"label": "Armored  –  Capability", "value": "00"},
            {"label": "Attack or Attack/Strike  –  Capability", "value": "00"},
            {"label": "Ballistic Missile/Ballistic Missile Defense Shooter  –  Capability", "value": "00"},
            {"label": "Bridge/Bridging  –  Capability", "value": "00"},
            {"label": "Cargo  –  Capability", "value": "00"},
            {"label": "Close Protection  –  Capability", "value": "00"},
            {"label": "Combat  –  Capability", "value": "00"},
            {"label": "Command and Control  –  Capability", "value": "00"},
            {"label": "Command Post Node  –  Capability", "value": "00"},
            {"label": "Crowd and Riot Control  –  Capability", "value": "00"},
            {"label": "Cyberspace  –  Capability", "value": "00"},
            {"label": "Directed Energy  –  Capability", "value": "00"},
            {"label": "Electromagnetic  –  Capability", "value": "00"},
            {"label": "Explosive Ordnance Disposal  –  Capability", "value": "00"},
            {"label": "Guided Missile  –  Capability", "value": "00"},
            {"label": "Heavy  –  Capability", "value": "00"},
            {"label": "Intelligence Surveillance Reconnaissance  –  Capability", "value": "00"},
            {"label": "Joint Network Node  –  Capability", "value": "00"},
            {"label": "Light  –  Capability", "value": "00"},
            {"label": "Maintenance  –  Capability", "value": "00"},
            {"label": "Medevac/Medic/Medical  –  Capability", "value": "00"},
            {"label": "Medium  –  Capability", "value": "00"},
            {"label": "Other Guided Missile  –  Capability", "value": "00"},
            {"label": "Petroleum/Petroleum Oil and Lubricants  –  Capability", "value": "00"},
            {"label": "Retransmission Site  –  Capability", "value": "00"},
            {"label": "Search and Rescue  –  Capability", "value": "00"},
            {"label": "Security  –  Capability", "value": "00"},
            {"label": "Sniper  –  Capability", "value": "00"},
            {"label": "Special Operations Forces  –  Capability", "value": "00"},
            {"label": "Special Weapons and Tactics (SWAT)  –  Capability", "value": "00"},
            {"label": "Utility  –  Capability", "value": "00"},
            {"label": "Water  –  Capability", "value": "00"},
            {"label": "Weapon or Weapons  –  Capability", "value": "00"},
            {"label": "Biological  –  CBRN", "value": "00"},
            {"label": "Chemical  –  CBRN", "value": "00"},
            {"label": "Decontamination  –  CBRN", "value": "00"},
            {"label": "Nuclear  –  CBRN", "value": "00"},
            {"label": "Radiological  –  CBRN", "value": "00"},
            {"label": "Accident  –  Composite Loss or Incident Qualifier", "value": "00"},
            {"label": "Assassination  –  Crime", "value": "00"},
            {"label": "Execution  –  Crime", "value": "00"},
            {"label": "Hijacker  –  Crime", "value": "00"},
            {"label": "Kidnapping  –  Crime", "value": "00"},
            {"label": "Piracy  –  Crime", "value": "00"},
            {"label": "Rape  –  Crime", "value": "00"},
            {"label": "Antisubmarine Warfare  –  Mission Area", "value": "00"},
            {"label": "Escort  –  Mission Area", "value": "00"},
            {"label": "Mine Countermeasures  –  Mission Area", "value": "00"},
            {"label": "Mine WarfareAPP-06 uses ‘MW’  –  Mission Area", "value": "00"},
            {"label": "Surface Warfare  –  Mission Area", "value": "00"},
            {"label": "Fixed Wing  –  Mobility (Not used by USAF)", "value": "00"},
            {"label": "Robotic  –  Mobility", "value": "00"},
            {"label": "Rotary Wing  –  Mobility", "value": "00"},
            {"label": "Tilt-Rotor  –  Mobility", "value": "00"},
            {"label": "Unmanned Aircraft (UA)/ Unmanned Aerial Vehicle (UAV)/ Unmanned Aircraft System (UAS)/ Remote Piloted Vehicle (RPV)  –  Mobility", "value": "00"},
            {"label": "VSTOL/VTOL or Helicopter Equipped  –  Mobility", "value": "00"},
            {"label": "Geostationary Orbit (GO)  –  Orbit", "value": "00"},
            {"label": "Geosynchronous Orbit (GSO)  –  Orbit", "value": "00"},
            {"label": "High Earth Orbit (HEO)  –  Orbit", "value": "00"},
            {"label": "Low Earth Orbit (LEO)  –  Orbit", "value": "00"},
            {"label": "Medium Earth Orbit (MEO)  –  Orbit", "value": "00"},
            {"label": "Molniya Orbit (MO)  –  Orbit", "value": "00"},
            {"label": "Civilian  –  Organization", "value": "00"},
            {"label": "Government Organization / Government Organization Member  –  Organization", "value": "00"},
            {"label": "Battalion  –  Support Level", "value": "00"},
            {"label": "Brigade  –  Support Level", "value": "00"},
            {"label": "Command  –  Support Level", "value": "00"},
            {"label": "Company  –  Support Level", "value": "00"},
            {"label": "Platoon/Detachment  –  Support Level", "value": "00"},
            {"label": "Regiment Group  –  Support Level", "value": "00"},
            {"label": "Section  –  Support Level", "value": "00"},
            {"label": "Squad  –  Support Level", "value": "00"},
            {"label": "Team/Crew  –  Support Level", "value": "00"}
        ],
        "SecondIconModifier": [
            {"label": "Unspecified", "value": "00"},
            {"label": "Electromagnetic Warfare (ASAT)  –  Only used with Anti-Satellite Weapon Main Icon", "value": "00"},
            {"label": "Autonomous Control  –  Capability", "value": "00"},
            {"label": "Close Range  –  Capability", "value": "00"},
            {"label": "Cyberspace  –  Capability", "value": "00"},
            {"label": "Expendable  –  Capability", "value": "00"},
            {"label": "Heavy  –  Capability", "value": "00"},
            {"label": "High Power Microwave (ASAT)Only used with Anti-Satellite Weapon Main Icon.  –  Capability", "value": "00"},
            {"label": "Laser (ASAT)  –  Capability (Only used with Anti-Satellite Weapon Main Icon)", "value": "00"},
            {"label": "Light  –  Capability", "value": "00"},
            {"label": "Light and Medium  –  Capability", "value": "00"},
            {"label": "Long Range  –  Capability", "value": "00"},
            {"label": "Maintenance  –  Capability", "value": "00"},
            {"label": "Medical Bed  –  Capability", "value": "00"},
            {"label": "Medium  –  Capability", "value": "00"},
            {"label": "Medium Range  –  Capability", "value": "00"},
            {"label": "Mine (ASAT)  –  Capability (Only used with Anti-Satellite Weapon Main Icon)", "value": "00"},
            {"label": "Mountain  –  Capability", "value": "00"},
            {"label": "Multifunctional  –  Capability", "value": "00"},
            {"label": "Railroad/Railway  –  Capability", "value": "00"},
            {"label": "Refuel  –  Capability", "value": "00"},
            {"label": "Remotely Piloted  –  Capability", "value": "00"},
            {"label": "Security Force Assistance  –  Capability", "value": "00"},
            {"label": "Short Range  –  Capability", "value": "00"},
            {"label": "Tug  –  Capability", "value": "00"},
            {"label": "Airborne  –  Mobility", "value": "00"},
            {"label": "Bicycle Equipped  –  Mobility", "value": "00"},
            {"label": "Fixed Wing  –  Mobility", "value": "00"},
            {"label": "Robotic  –  Mobility", "value": "00"},
            {"label": "Rotary Wing  –  Mobility", "value": "00"},
            {"label": "Ski  –  Mobility", "value": "00"},
            {"label": "Tracked  –  Mobility", "value": "00"},
            {"label": "Wheeled (Limited Cross Country)  –  Mobility", "value": "00"},
            {"label": "Wheeled X (Cross Country)  –  Mobility", "value": "00"},
            {"label": "Infrared  –  Sensor (Only used with satellite icons)", "value": "00"},
            {"label": "Optical  –  Sensor (Only used with satellite icons)", "value": "00"},
            {"label": "Radar  –  Sensor (Only used with satellite icons)", "value": "00"},
            {"label": "Signals Intelligence (SIGINT)  –  Sensor (Only used with satellite icons)", "value": "00"}
        ],
        "EchelonMobility": [
            {"label": "Not Applicable", "value": "00"}
        ],
        "HeadquartersTaskforceDummy": [
            {"label": "Unspecified", "value": "0"},
            {"label": "Feint / Dummy", "value": "1"},
            {"label": "Headquarters", "value": "2"},
            {"label": "Feint / Dummy Headquarters", "value": "3"},
            {"label": "Task Force", "value": "4"},
            {"label": "Feint / Dummy Task Force", "value": "5"},
            {"label": "Task Force Headquarters", "value": "6"},
            {"label": "Feint / Dummy Task Force Headquarters", "value": "7"}
        ]
    },
        
    "SPACE_MISSILE": {
        "MainIcon": [
            {"label": "Missile", "value": "00"}
        ],
        "FirstIconModifier": [
            {"label": "Unspecified", "value": "00"},
            {"label": "Space  –  Launch Origin", "value": "00"},
            {"label": "Ballistic  –  Missile Class", "value": "00"},
            {"label": "Hypersonic  –  Missile Class", "value": "00"},
            {"label": "Interceptor  –  Missile Class", "value": "00"}
        ],
        "SecondIconModifier": [
            {"label": "Cyberspace  –  Capability", "value": "00"},
            {"label": "Expendable  –  Capability", "value": "00"},
            {"label": "Heavy  –  Capability", "value": "00"},
            {"label": "Light  –  Capability", "value": "00"},
            {"label": "Light and Medium  –  Capability", "value": "00"},
            {"label": "Long Range  –  Capability", "value": "00"},
            {"label": "Medical Bed  –  Capability", "value": "00"},
            {"label": "Medium  –  Capability", "value": "00"},
            {"label": "Medium Range  –  Capability", "value": "00"},
            {"label": "Mountain  –  Capability", "value": "00"},
            {"label": "Multifunctional  –  Capability", "value": "00"},
            {"label": "Railroad/Railway  –  Capability", "value": "00"},
            {"label": "Remotely Piloted  –  Capability", "value": "00"},
            {"label": "Security Force Assistance  –  Capability", "value": "00"},
            {"label": "Short Range  –  Capability", "value": "00"},
            {"label": "Space  –  Launch Origin", "value": "00"},
            {"label": "Close Range (CRBM)  –  Missile Range", "value": "00"},
            {"label": "Intercontinental  –  Missile Range (5500km or greater)", "value": "00"},
            {"label": "Intermediate Range  –  Missile Range (1000km to 3500km)", "value": "00"},
            {"label": "Long Range  –  Missile Range (3500km to 5500km)", "value": "00"},
            {"label": "Medium Range  –  Missile Range (1000km to 3500km)", "value": "00"},
            {"label": "Short Range  –  Missile Range (1000km or less)", "value": "00"},
            {"label": "Arrow  –  Missile Type-BMD (Used with Interceptor modifier 1 only)", "value": "00"},
            {"label": "Debris  –  Missile Type-BMD", "value": "00"},
            {"label": "Ground-Based Interceptor (GBI)  –  Missile Type-BMD (Used with Interceptor modifier 1 only)", "value": "00"},
            {"label": "Patriot  –  Missile Type-BMD (Used with Interceptor modifier 1 only)", "value": "00"},
            {"label": "Standard Missile Terminal Phase (SM-T)  –  Missile Type-BMD (Used with Interceptor modifier 1 only)", "value": "00"},
            {"label": "Standard Missile-3 (SM-3)  –  Missile Type-BMD (Used with Interceptor modifier 1 only)", "value": "00"},
            {"label": "Terminal High Altitude Area Defense (THAAD)  –  Missile Type-BMD (Used with Interceptor modifier 1 only)", "value": "00"},
            {"label": "Unknown  –  Missile Type-BMD", "value": "00"},
            {"label": "Airborne  –  Mobility", "value": "00"},
            {"label": "Bicycle Equipped  –  Mobility", "value": "00"},
            {"label": "Fixed Wing  –  Mobility", "value": "00"},
            {"label": "Robotic  –  Mobility", "value": "00"},
            {"label": "Rotary Wing  –  Mobility", "value": "00"},
            {"label": "Ski  –  Mobility", "value": "00"},
            {"label": "Tracked  –  Mobility", "value": "00"},
            {"label": "Wheeled (Limited Cross Country)  –  Mobility", "value": "00"},
            {"label": "Wheeled X (Cross Country)  –  Mobility", "value": "00"}
        ],
        "EchelonMobility": [
            {"label": "Not Applicable", "value": "00"}
        ],
        "HeadquartersTaskforceDummy": [
            {"label": "Unspecified", "value": "0"},
            {"label": "Feint / Dummy", "value": "1"},
            {"label": "Headquarters", "value": "2"},
            {"label": "Feint / Dummy Headquarters", "value": "3"},
            {"label": "Task Force", "value": "4"},
            {"label": "Feint / Dummy Task Force", "value": "5"},
            {"label": "Task Force Headquarters", "value": "6"},
            {"label": "Feint / Dummy Task Force Headquarters", "value": "7"}
        ]
    },
    
    "LAND_UNIT": {
        "MainIcon": [
            {"label": "Unspecified", "value": "000000"},
            {"label": "Command and Control  –  Reserved for Amplifier field Special Headquarters", "value": "110000"},
            {"label": "Broadcast Transmitter Antennae  –  Command and Control", "value": "000000"},
            {"label": "Civil Affairs  –  Command and Control", "value": "000000"},
            {"label": "Civil-Military Cooperation  –  Command and Control", "value": "000000"},
            {"label": "Information Operations  –  Command and Control", "value": "000000"},
            {"label": "Liaison  –  Command and Control", "value": "000000"},
            {"label": "Reconnaissance and Liaison Element  –  Command and Control (Liaison)", "value": "000000"},
            {"label": "Military Information Support Operations (MISO)  –  Command and Control", "value": "000000"},
            {"label": "Broadcast Transmitter Antennae  –  Command and Control (Military Information Support Operations (MISO))", "value": "000000"},
            {"label": "Radio  –  Command and Control", "value": "000000"},
            {"label": "Radio Relay  –  Command and Control", "value": "000000"},
            {"label": "Radio Teletype Center  –  Command and Control", "value": "000000"},
            {"label": "Signal  –  Command and Control", "value": "000000"},
            {"label": "Radio  –  Command and Control-Signal", "value": "000000"},
            {"label": "Radio Relay  –  Command and Control-Signal", "value": "000000"},
            {"label": "Teletype  –  Command and Control-Signal", "value": "000000"},
            {"label": "Video Imagery (Combat Camera)  –  Command and Control-Signal", "value": "000000"},
            {"label": "Video Imagery (Combat Camera)  –  Command and Control", "value": "000000"},
            {"label": "Space  –  Command and Control", "value": "0000"},
            {"label": "Special Troops  –  Command and Control", "value": "0000"},
            {"label": "Multi-Domain Operations  –  Command and Control", "value": "0000"},
            {"label": "Air Assault with Organic Lift  –  Movement and Maneuver", "value": "0000"},
            {"label": "Air Traffic Services/Airfield Operations  –  Movement and Maneuver", "value": "0000"},
            {"label": "Antitank/Antiarmor  –  Movement and Maneuver", "value": "0000"},
            {"label": "Armored  –  Movement and Maneuver-Antitank/Antiarmor", "value": "0000"},
            {"label": "Motorized  –  Movement and Maneuver-Antitank/Antiarmor", "value": "0000"},
            {"label": "Armor /Mechanized  –  Movement and Maneuver", "value": "0000"},
            {"label": "Reconnaissance/Cavalry/Scout  –  Movement and Maneuver-Armor /Mechanized", "value": "0000"},
            {"label": "Amphibious  –  Movement and Maneuver-Armor /Mechanized", "value": "0000"},
            {"label": "Army Aviation/Aviation Rotary Wing  –  Movement and Maneuver", "value": "0000"},
            {"label": "Reconnaissance  –  Movement and Maneuver-Army Aviation/Aviation Rotary Wing", "value": "0000"},
            {"label": "Aviation Composite  –  Movement and Maneuver", "value": "0000"},
            {"label": "Aviation Fixed Wing  –  Movement and Maneuver", "value": "0000"},
            {"label": "Reconnaissance  –  Movement and Maneuver-Aviation Fixed Wing", "value": "0000"},
            {"label": "Combat  –  Movement and Maneuver", "value": "0000"},
            {"label": "Combined Arms  –  Movement and Maneuver", "value": "0000"},
            {"label": "Infantry  –  Movement and Maneuver", "value": "0000"},
            {"label": "Amphibious  –  Movement and Maneuver-Infantry", "value": "0000"},
            {"label": "Armored/Mechanized/Tracked  –  Movement and Maneuver-Infantry", "value": "0000"},
            {"label": "Main Gun System  –  Movement and Maneuver-Infantry", "value": "0000"},
            {"label": "Motorized  –  Movement and Maneuver-Infantry", "value": "0000"},
            {"label": "Infantry Fighting Vehicle  –  Movement and Maneuver-Infantry", "value": "0000"},
            {"label": "Mobile Gun System  –  Movement and Maneuver-Infantry", "value": "0000"},
            {"label": "Observer  –  Movement and Maneuver", "value": "0000"},
            {"label": "Reconnaissance/Cavalry/Scout  –  Movement and Maneuver", "value": "0000"},
            {"label": "Reconnaissance and Surveillance  –  Movement and Maneuver-Reconnaissance/Cavalry/Scout", "value": "0000"},
            {"label": "Marine  –  Movement and Maneuver-Reconnaissance/Cavalry/Scout", "value": "0000"},
            {"label": "Motorized  –  Movement and Maneuver-Reconnaissance/Cavalry/Scout", "value": "0000"},
            {"label": "Sea Air Land (SEAL)  –  Movement and Maneuver", "value": "0000"},
            {"label": "Sniper  –  Movement and Maneuver", "value": "0000"},
            {"label": "Surveillance  –  Movement and Maneuver", "value": "0000"},
            {"label": "Special Forces  –  Movement and Maneuver", "value": "0000"},
            {"label": "Special Operations Forces (SOF)  –  Movement and Maneuver", "value": "0000"},
            {"label": "Fixed Wing MISO  –  Movement and Maneuver-Special Operations Forces (SOF)", "value": "0000"},
            {"label": "Ground  –  Movement and Maneuver-Special Operations Forces (SOF)", "value": "0000"},
            {"label": "Underwater Demolition  –  Movement and Maneuver-Special Operations Forces (SOF)", "value": "0000"},
            {"label": "Unmanned Aerial Systems  –  Movement and Maneuver", "value": "0000"},
            {"label": "Ranger  –  Movement and Maneuver", "value": "0000"},
            {"label": "Air Defense  –  Fires", "value": "0000"},
            {"label": "Main Gun System  –  Fires-Air Defense", "value": "0000"},
            {"label": "Missile  –  Fires-Air Defense", "value": "0000"},
            {"label": "Air and Missile Defense  –  Fires-Air Defense", "value": "0000"},
            {"label": "Air/Land Naval Gunfire Liaison  –  Fires", "value": "0000"},
            {"label": "Field Artillery  –  Fires", "value": "0000"},
            {"label": "Self-propelledRemoved from 2525E  –  Fires (Field Artillery)", "value": "0000"},
            {"label": "Field Artillery Observer  –  Fires", "value": "0000"},
            {"label": "Joint Fire Support  –  Fires", "value": "0000"},
            {"label": "Meteorological  –  Fires", "value": "0000"},
            {"label": "Missile  –  Fires", "value": "0000"},
            {"label": "Mortar  –  Fires", "value": "0000"},
            {"label": "Self-Propelled Wheeled  –  Fires (Mortar)", "value": "0000"},
            {"label": "Survey  –  Fires", "value": "0000"},
            {"label": "Chemical Biological Radiological Nuclear Defense  –  Protection", "value": "0000"},
            {"label": "Motorized  –  Protection (Chemical Biological Radiological Nuclear Defense)", "value": "0000"},
            {"label": "Reconnaissance  –  Protection-Chemical Biological Radiological Nuclear Defense", "value": "0000"},
            {"label": "Reconnaissance Equipped  –  Protection-Chemical Biological Radiological Nuclear Defense", "value": "0000"},
            {"label": "Chemical, Biological, Radiological, Nuclear, and High-Yield Explosives  –  Protection-Chemical Biological Radiological Nuclear Defense", "value": "0000"},
            {"label": "Combat Support (Maneuver Enhancement)  –  Protection", "value": "0000"},
            {"label": "Criminal Investigation Division  –  Protection", "value": "0000"},
            {"label": "Diving  –  Protection", "value": "0000"},
            {"label": "Dog  –  Protection", "value": "0000"},
            {"label": "Drilling  –  Protection", "value": "0000"},
            {"label": "Engineer  –  Protection", "value": "0000"},
            {"label": "Mechanized  –  Protection-Engineer", "value": "0000"},
            {"label": "Protection  –  Engineer-Motorized (Protection-Engineer)", "value": "0000"},
            {"label": "Protection  –  Engineer-Reconnaissance (Protection-Engineer)", "value": "0000"},
            {"label": "Explosive Ordnance Disposal (EOD)  –  Protection", "value": "0000"},
            {"label": "Field Camp Construction  –  Protection", "value": "0000"},
            {"label": "Fire Fighting/Fire Protection  –  Protection", "value": "0000"},
            {"label": "Geospatial Support/Geospatial Information Support  –  Protection", "value": "0000"},
            {"label": "Military Police  –  Protection", "value": "0000"},
            {"label": "Mine  –  Protection", "value": "0000"},
            {"label": "Mine Clearing  –  Protection", "value": "0000"},
            {"label": "Mine Launching  –  Protection", "value": "0000"},
            {"label": "Mine Laying  –  Protection", "value": "0000"},
            {"label": "Security  –  Protection", "value": "0000"},
            {"label": "Motorized  –  Protection-Security", "value": "0000"},
            {"label": "Search and Rescue  –  Protection", "value": "0000"},
            {"label": "Isolated Personnel  –  Protection-Search and Rescue", "value": "0000"},
            {"label": "Shore Patrol/Security Police  –  Protection", "value": "0000"},
            {"label": "Topographic/Geospatial  –  Protection", "value": "0000"},
            {"label": "Missile Defense  –  Protection", "value": "0000"},
            {"label": "Analysis  –  Intelligence", "value": "0000"},
            {"label": "Counterintelligence  –  Intelligence", "value": "0000"},
            {"label": "Direction Finding  –  Intelligence", "value": "0000"},
            {"label": "Electronic Ranging  –  Intelligence", "value": "0000"},
            {"label": "Electronic Warfare  –  Intelligence", "value": "0000"},
            {"label": "Analysis  –  Intelligence-Electronic Warfare", "value": "0000"},
            {"label": "Direction Finding  –  Intelligence-Electronic Warfare", "value": "0000"},
            {"label": "Intercept  –  Intelligence-Electronic Warfare", "value": "0000"},
            {"label": "Jamming  –  Intelligence-Electronic Warfare", "value": "0000"},
            {"label": "Search  –  Intelligence-Electronic Warfare", "value": "0000"},
            {"label": "Intercept (Search and Recording)  –  Intelligence", "value": "0000"},
            {"label": "Interrogation  –  Intelligence", "value": "0000"},
            {"label": "Jamming  –  Intelligence", "value": "0000"},
            {"label": "Joint Intelligence Center  –  Intelligence", "value": "0000"},
            {"label": "Military Intelligence  –  Intelligence", "value": "0000"},
            {"label": "Search  –  Intelligence", "value": "0000"},
            {"label": "Sensor  –  Intelligence", "value": "0000"},
            {"label": "Military History  –  Intelligence", "value": "0000"},
            {"label": "Sustainment", "value": "0000"},
            {"label": "Administrative  –  Sustainment", "value": "0000"},
            {"label": "All Classes of Supply  –  Sustainment", "value": "0000"},
            {"label": "Ammunition  –  Sustainment", "value": "0000"},
            {"label": "Band  –  Sustainment", "value": "0000"},
            {"label": "Army Music  –  Sustainment-Band", "value": "0000"},
            {"label": "Combat Service Support  –  Sustainment", "value": "0000"},
            {"label": "Finance  –  Sustainment", "value": "0000"},
            {"label": "Judge Advocate General  –  Sustainment", "value": "0000"},
            {"label": "Labor  –  Sustainment", "value": "0000"},
            {"label": "Laundry/Bath  –  Sustainment", "value": "0000"},
            {"label": "Maintenance  –  Sustainment", "value": "0000"},
            {"label": "Material  –  Sustainment", "value": "0000"},
            {"label": "Medical  –  Sustainment", "value": "0000"},
            {"label": "Medical Treatment Facility  –  Sustainment", "value": "0000"},
            {"label": "Morale, Welfare and Recreation  –  Sustainment", "value": "0000"},
            {"label": "Mortuary Affairs  –  Sustainment", "value": "0000"},
            {"label": "Multiple Classes of Supply  –  Sustainment", "value": "0000"},
            {"label": "NATO Supply Class I  –  Sustainment", "value": "0000"},
            {"label": "NATO Supply Class II  –  Sustainment", "value": "0000"},
            {"label": "NATO Supply Class III  –  Sustainment", "value": "0000"},
            {"label": "NATO Supply Class IV  –  Sustainment", "value": "0000"},
            {"label": "NATO Supply Class V  –  Sustainment", "value": "0000"},
            {"label": "Ordnance  –  Sustainment", "value": "0000"},
            {"label": "Personnel Services  –  Sustainment", "value": "0000"},
            {"label": "Petroleum, Oil and Lubricants  –  Sustainment", "value": "0000"},
            {"label": "Public Affairs/Public Information  –  Sustainment", "value": "0000"},
            {"label": "Quartermaster  –  Sustainment", "value": "0000"},
            {"label": "Religious Support  –  Sustainment", "value": "0000"},
            {"label": "Replacement Holding Unit  –  Sustainment", "value": "0000"},
            {"label": "Joint Information Bureau (JIB)  –  Sustainment", "value": "0000"},
            {"label": "Transportation  –  Sustainment", "value": "0000"},
            {"label": "US Supply Class I  –  Sustainment", "value": "0000"},
            {"label": "US Supply Class IV  –  Sustainment", "value": "0000"},
            {"label": "US Supply Class VI  –  Sustainment", "value": "0000"},
            {"label": "US Supply Class VII  –  Sustainment", "value": "0000"},
            {"label": "US Supply Class VIII  –  Sustainment", "value": "0000"},
            {"label": "US Supply Class IX  –  Sustainment", "value": "0000"},
            {"label": "US Supply Class X  –  Sustainment", "value": "0000"},
            {"label": "Water Purification  –  Sustainment", "value": "0000"},
            {"label": "Broadcast  –  Sustainment", "value": "0000"},
            {"label": "Interpreter/Translator  –  Sustainment", "value": "0000"},
            {"label": "Support  –  Sustainment", "value": "0000"},
            {"label": "Army Field Support  –  Sustainment", "value": "0000"},
            {"label": "Contracting Services  –  Sustainment", "value": "0000"},
            {"label": "Parachute Rigger  –  Sustainment", "value": "0000"},
            {"label": "Human Resources  –  Sustainment", "value": "0000"},
            {"label": "Naval  –  Naval", "value": "0000"},
            {"label": "Allied Command Europe Rapid Reaction Corps (ARRC)  –  Named Headquarters", "value": "0000"},
            {"label": "Allied Command Operations  –  Named Headquarters", "value": "0000"},
            {"label": "International Security Assistance Force (ISAF)  –  Named Headquarters", "value": "0000"},
            {"label": "Multinational (MN)  –  Named Headquarters", "value": "0000"},
            {"label": "Emergency Operation", "value": "0000"},
            {"label": "Law Enforcement", "value": "0000"},
            {"label": "Bureau of Alcohol, Tobacco, Firearms and Explosives (ATF) (Department of Justice)  –  Law Enforcement", "value": "0000"},
            {"label": "Border Patrol  –  Law Enforcement", "value": "0000"},
            {"label": "Customs Service  –  Law Enforcement", "value": "0000"},
            {"label": "Drug Enforcement Administration (DEA)  –  Law Enforcement", "value": "0000"},
            {"label": "Department of Justice (DOJ)  –  Law Enforcement", "value": "0000"},
            {"label": "Federal Bureau of Investigation (FBI)  –  Law Enforcement", "value": "0000"},
            {"label": "Police  –  Law Enforcement", "value": "0000"},
            {"label": "Prison  –  Law Enforcement", "value": "0000"},
            {"label": "United States Secret Service (Treas) (USSS)  –  Law Enforcement", "value": "0000"},
            {"label": "Transportation Security Administration (TSA)  –  Law Enforcement", "value": "0000"},
            {"label": "Coast Guard  –  Law Enforcement", "value": "0000"},
            {"label": "US Marshals Service  –  Law Enforcement", "value": "0000"},
            {"label": "Internal Security Force  –  Law Enforcement", "value": "0000"},
            {"label": "Cyber", "value": "0000"}
        ],
        "FirstIconModifier": [
            {"label": "Unspecified", "value": "000"},
            {"label": "Headquarters or Headquarters Staff Element", "value": "098"},
            {"label": "Airfield, Aerial Port of Debarkation, or Aerial Port of Embarkation  –  Capability", "value": "0000"},
            {"label": "Amphibious Warfare Ship  –  Capability", "value": "0000"},
            {"label": "Area  –  Capability", "value": "0000"},
            {"label": "Armored  –  Capability", "value": "0000"},
            {"label": "Assault  –  Capability", "value": "0000"},
            {"label": "Attack or Attack/Strike  –  Capability", "value": "0000"},
            {"label": "Ballistic Missile/Ballistic Missile Defense Shooter  –  Capability", "value": "0000"},
            {"label": "Biological  –  Capability", "value": "0000"},
            {"label": "Border  –  Capability", "value": "0000"},
            {"label": "Bridge/Bridging  –  Capability", "value": "0000"},
            {"label": "Cargo  –  Capability", "value": "0000"},
            {"label": "Close Protection  –  Capability", "value": "0000"},
            {"label": "Combat  –  Capability", "value": "0000"},
            {"label": "Command and Control  –  Capability", "value": "0000"},
            {"label": "Command Post Node  –  Capability", "value": "0000"},
            {"label": "Communications Contingency Package  –  Capability", "value": "0000"},
            {"label": "Construction  –  Capability", "value": "0000"},
            {"label": "Criminal Investigation Division  –  Capability", "value": "0000"},
            {"label": "Cross Cultural Communication  –  Capability", "value": "0000"},
            {"label": "Crowd and Riot Control  –  Capability", "value": "0000"},
            {"label": "Cyberspace  –  Capability", "value": "0000"},
            {"label": "Detention  –  Capability", "value": "0000"},
            {"label": "Digital  –  Capability", "value": "0000"},
            {"label": "Direct Communications  –  Capability", "value": "0000"},
            {"label": "Directed Energy  –  Capability", "value": "0000"},
            {"label": "Diving  –  Capability", "value": "0000"},
            {"label": "Dog  –  Capability", "value": "0000"},
            {"label": "Drilling  –  Capability", "value": "0000"},
            {"label": "Electromagnetic  –  Capability", "value": "0000"},
            {"label": "Electro-Optical  –  Capability", "value": "0000"},
            {"label": "Enhanced  –  Capability", "value": "0000"},
            {"label": "Explosive Ordnance Disposal  –  Capability", "value": "0000"},
            {"label": "Fire Direction Center  –  Capability", "value": "0000"},
            {"label": "Force  –  Capability", "value": "0000"},
            {"label": "Forward  –  Capability", "value": "0000"},
            {"label": "Ground Station Module  –  Capability", "value": "0000"},
            {"label": "Guided Missile  –  Capability", "value": "0000"},
            {"label": "Heavy  –  Capability", "value": "0000"},
            {"label": "Intelligence Surveillance Reconnaissance  –  Capability", "value": "0000"},
            {"label": "Joint Network Node  –  Capability", "value": "0000"},
            {"label": "Landing Support  –  Capability", "value": "0000"},
            {"label": "Light  –  Capability", "value": "0000"},
            {"label": "Load Handling System  –  Capability", "value": "0000"},
            {"label": "Maintenance  –  Capability", "value": "0000"},
            {"label": "Medevac/Medic/Medical  –  Capability", "value": "0000"},
            {"label": "Medium  –  Capability", "value": "0000"},
            {"label": "Meteorological  –  Capability", "value": "0000"},
            {"label": "Missile  –  Capability", "value": "0000"},
            {"label": "Mobile Advisor and Support  –  Capability", "value": "0000"},
            {"label": "Mobile Subscriber Equipment  –  Capability", "value": "0000"},
            {"label": "Mobility Assault  –  Capability", "value": "0000"},
            {"label": "Mobility Support  –  Capability", "value": "0000"},
            {"label": "Multi-Domain Operations  –  Capability", "value": "0000"},
            {"label": "Multinational  –  Capability", "value": "0000"},
            {"label": "Multinational Specialized Unit  –  Capability", "value": "0000"},
            {"label": "Multiple Rocket Launcher  –  Capability", "value": "0000"},
            {"label": "NATO Medical Role 1  –  Capability", "value": "0000"},
            {"label": "NATO Medical Role 2  –  Capability", "value": "0000"},
            {"label": "NATO Medical Role 2 Basic  –  Capability", "value": "0000"},
            {"label": "NATO Medical Role 2 Enhanced  –  Capability", "value": "0000"},
            {"label": "NATO Medical Role 3  –  Capability", "value": "0000"},
            {"label": "NATO Medical Role 4  –  Capability", "value": "0000"},
            {"label": "NATO Medical Role Forward  –  Capability", "value": "0000"},
            {"label": "Naval  –  Capability", "value": "0000"},
            {"label": "Network or Network Operations  –  Capability", "value": "0000"},
            {"label": "Operations  –  Capability", "value": "0000"},
            {"label": "Other Guided Missile  –  Capability", "value": "0000"},
            {"label": "Palletized Load System  –  Capability", "value": "0000"},
            {"label": "Petroleum/Petroleum Oil and Lubricants  –  Capability", "value": "0000"},
            {"label": "Pipeline  –  Capability", "value": "0000"},
            {"label": "Postal  –  Capability", "value": "0000"},
            {"label": "Radar  –  Capability", "value": "0000"},
            {"label": "Radio Frequency Identification (RFID) Interrogator / Sensor  –  Capability", "value": "0000"},
            {"label": "Retransmission Site  –  Capability", "value": "0000"},
            {"label": "Route, Reconnaissance, and Clearance  –  Capability", "value": "0000"},
            {"label": "Search and Rescue  –  Capability", "value": "0000"},
            {"label": "Security  –  Capability", "value": "0000"},
            {"label": "Sensor  –  Capability", "value": "0000"},
            {"label": "Signals Intelligence  –  Capability", "value": "0000"},
            {"label": "Single Rocket Launcher  –  Capability", "value": "0000"},
            {"label": "Smoke  –  Capability", "value": "0000"},
            {"label": "Sniper  –  Capability", "value": "0000"},
            {"label": "Sound Ranging  –  Capability", "value": "0000"},
            {"label": "Special Operations Forces  –  Capability", "value": "0000"},
            {"label": "Special Weapons and Tactics (SWAT)  –  Capability", "value": "0000"},
            {"label": "Support  –  Capability", "value": "0000"},
            {"label": "Survey  –  Capability", "value": "0000"},
            {"label": "Tactical Exploitation  –  Capability", "value": "0000"},
            {"label": "Tactical Satellite Communications  –  Capability", "value": "0000"},
            {"label": "Target Acquisition  –  Capability", "value": "0000"},
            {"label": "Topographic/Geospatial  –  Capability", "value": "0000"},
            {"label": "Unmanned Aerial Systems (UAS)  –  Capability", "value": "0000"},
            {"label": "Utility  –  Capability", "value": "0000"},
            {"label": "Video Imagery (Combat Camera)  –  Capability", "value": "0000"},
            {"label": "Water  –  Capability", "value": "0000"},
            {"label": "Weapon  –  Capability", "value": "0000"},
            {"label": "Weapon or Weapons  –  Capability", "value": "0000"},
            {"label": "Biological  –  CBRN", "value": "0000"},
            {"label": "Chemical  –  CBRN", "value": "0000"},
            {"label": "Decontamination  –  CBRN", "value": "0000"},
            {"label": "Nuclear  –  CBRN", "value": "0000"},
            {"label": "Radiological  –  CBRN", "value": "0000"},
            {"label": "Accident  –  Composite Loss or Incident Qualifier", "value": "0000"},
            {"label": "Assassination  –  Crime", "value": "0000"},
            {"label": "Execution  –  Crime", "value": "0000"},
            {"label": "Hijacker  –  Crime", "value": "0000"},
            {"label": "Kidnapping  –  Crime", "value": "0000"},
            {"label": "Piracy  –  Crime", "value": "0000"},
            {"label": "Rape  –  Crime", "value": "0000"},
            {"label": "Antisubmarine Warfare  –  Mission Area", "value": "0000"},
            {"label": "Escort  –  Mission Area", "value": "0000"},
            {"label": "Mine Countermeasures  –  Mission Area", "value": "0000"},
            {"label": "Mine WarfareAPP-06 uses ‘MW’  –  Mission Area", "value": "0000"},
            {"label": "Surface Warfare  –  Mission Area", "value": "0000"},
            {"label": "Fixed Wing –  Mobility (Not used by USAF)", "value": "0000"},
            {"label": "Robotic  –  Mobility", "value": "0000"},
            {"label": "Rotary Wing  –  Mobility", "value": "0000"},
            {"label": "Tilt-Rotor  –  Mobility", "value": "0000"},
            {"label": "Unmanned Aircraft (UA)/ Unmanned Aerial Vehicle (UAV)/ Unmanned Aircraft System (UAS)/ Remote Piloted Vehicle (RPV)  –  Mobility", "value": "0000"},
            {"label": "VSTOL/VTOL or Helicopter Equipped  –  Mobility", "value": "0000"},
            {"label": "Civilian  –  Organization", "value": "0000"},
            {"label": "Government Organization / Government Organization Member  –  Organization", "value": "0000"},
            {"label": "Army or Theater Army  –  Support Level", "value": "0000"},
            {"label": "Battalion  –  Support Level", "value": "0000"},
            {"label": "Brigade  –  Support Level", "value": "0000"},
            {"label": "Command  –  Support Level", "value": "0000"},
            {"label": "Company  –  Support Level", "value": "0000"},
            {"label": "Corps  –  Support Level", "value": "0000"},
            {"label": "Division  –  Support Level", "value": "0000"},
            {"label": "Independent Command  –  Support Level", "value": "0000"},
            {"label": "Platoon/Detachment  –  Support Level", "value": "0000"},
            {"label": "Regiment Group  –  Support Level", "value": "0000"},
            {"label": "Section  –  Support Level", "value": "0000"},
            {"label": "Squad  –  Support Level", "value": "0000"},
            {"label": "Team/Crew  –  Support Level", "value": "0000"},
            {"label": "Theater  –  Support Level", "value": "0000"}
        ],
        "SecondIconModifier": [
            {"label": "Unspecified", "value": "000"},
            {"label": "Supply  –  Capability", "value": "062"},
            {"label": "Air Defense  –  Capability", "value": "0000"},
            {"label": "Attack  –  Capability", "value": "0000"},
            {"label": "Autonomous Control  –  Capability", "value": "0000"},
            {"label": "Battle Damage Repair  –  Capability", "value": "0000"},
            {"label": "Blood  –  Capability", "value": "0000"},
            {"label": "Casualty Staging  –  Capability", "value": "0000"},
            {"label": "Clearing  –  Capability", "value": "0000"},
            {"label": "Close Range  –  Capability", "value": "0000"},
            {"label": "Combat and Operational Stress Control  –  Capability", "value": "0000"},
            {"label": "Combat Search and Rescue  –  Capability", "value": "0000"},
            {"label": "Composite  –  Capability", "value": "0000"},
            {"label": "Control  –  Capability", "value": "0000"},
            {"label": "Cyberspace  –  Capability", "value": "0000"},
            {"label": "Decontamination  –  Capability", "value": "0000"},
            {"label": "Demolition  –  Capability", "value": "0000"},
            {"label": "Dental  –  Capability", "value": "0000"},
            {"label": "Digital  –  Capability", "value": "0000"},
            {"label": "Enhanced Position Location Reporting System (EPLRS)  –  Capability", "value": "0000"},
            {"label": "Equipment  –  Capability", "value": "0000"},
            {"label": "Expendable  –  Capability", "value": "0000"},
            {"label": "Guerilla  –  Capability", "value": "0000"},
            {"label": "Heavy  –  Capability", "value": "0000"},
            {"label": "High Altitude  –  Capability", "value": "0000"},
            {"label": "High to Low Altitude  –  Capability", "value": "0000"},
            {"label": "High to Medium Altitude  –  Capability", "value": "0000"},
            {"label": "Intensive Care  –  Capability", "value": "0000"},
            {"label": "Intermodal  –  Capability", "value": "0000"},
            {"label": "Jamming  –  Capability", "value": "0000"},
            {"label": "Laboratory  –  Capability", "value": "0000"},
            {"label": "Launcher  –  Capability", "value": "0000"},
            {"label": "Light  –  Capability", "value": "0000"},
            {"label": "Light and Medium  –  Capability", "value": "0000"},
            {"label": "Long Range  –  Capability", "value": "0000"},
            {"label": "Low Altitude  –  Capability", "value": "0000"},
            {"label": "Medical Bed  –  Capability", "value": "0000"},
            {"label": "Medium  –  Capability", "value": "0000"},
            {"label": "Medium Altitude  –  Capability", "value": "0000"},
            {"label": "Medium Range  –  Capability", "value": "0000"},
            {"label": "Medium to Low Altitude  –  Capability", "value": "0000"},
            {"label": "Mountain  –  Capability", "value": "0000"},
            {"label": "Multifunctional  –  Capability", "value": "0000"},
            {"label": "Multi–Channel  –  Capability", "value": "0000"},
            {"label": "Optical (Flash)  –  Capability", "value": "0000"},
            {"label": "Optometry  –  Capability", "value": "0000"},
            {"label": "Pack Animal  –  Capability", "value": "0000"},
            {"label": "Patient Evacuation Coordination  –  Capability", "value": "0000"},
            {"label": "Preventive Maintenance  –  Capability", "value": "0000"},
            {"label": "Preventive Medicine  –  Capability", "value": "0000"},
            {"label": "Psychological  –  Capability", "value": "0000"},
            {"label": "Radio Relay Line of Sight  –  Capability", "value": "0000"},
            {"label": "Railroad/Railway  –  Capability", "value": "0000"},
            {"label": "Recovery (Maintenance)  –  Capability", "value": "0000"},
            {"label": "Recovery (Unmanned Systems)  –  Capability", "value": "0000"},
            {"label": "Refuel  –  Capability", "value": "0000"},
            {"label": "Remotely Piloted  –  Capability", "value": "0000"},
            {"label": "Rescue Coordination Center  –  Capability", "value": "0000"},
            {"label": "Security Force Assistance  –  Capability", "value": "0000"},
            {"label": "Shelter  –  Capability", "value": "0000"},
            {"label": "Short Range  –  Capability", "value": "0000"},
            {"label": "Single Channel  –  Capability", "value": "0000"},
            {"label": "Strategic  –  Capability", "value": "0000"},
            {"label": "Support  –  Capability", "value": "0000"},
            {"label": "Surface Deployment and Distribution Command  –  Capability", "value": "0000"},
            {"label": "Surgical  –  Capability", "value": "0000"},
            {"label": "Tactical  –  Capability", "value": "0000"},
            {"label": "Troop  –  Capability", "value": "0000"},
            {"label": "Utility  –  Capability", "value": "0000"},
            {"label": "Very Heavy  –  Capability", "value": "0000"},
            {"label": "Veterinary  –  Capability", "value": "0000"},
            {"label": "Air Assault  –  Mobility", "value": "0000"},
            {"label": "Airborne  –  Mobility", "value": "0000"},
            {"label": "Amphibious  –  Mobility", "value": "0000"},
            {"label": "Arctic  –  Mobility", "value": "0000"},
            {"label": "Bicycle Equipped  –  Mobility", "value": "0000"},
            {"label": "Fixed Wing  –  Mobility", "value": "0000"},
            {"label": "Landing Craft  –  Mobility", "value": "0000"},
            {"label": "Landing Ship  –  Mobility", "value": "0000"},
            {"label": "Launch  –  Mobility", "value": "0000"},
            {"label": "Navy Barge, Not Self-Propelled  –  Mobility", "value": "0000"},
            {"label": "Navy Barge, Self-Propelled  –  Mobility", "value": "0000"},
            {"label": "Noncombatant Generic Vessel  –  Mobility", "value": "0000"},
            {"label": "Ocean Going Tug Boat  –  Mobility", "value": "0000"},
            {"label": "Riverine  –  Mobility", "value": "0000"},
            {"label": "Robotic  –  Mobility", "value": "0000"},
            {"label": "Rotary Wing  –  Mobility", "value": "0000"},
            {"label": "Service Craft/Yard  –  Mobility", "value": "0000"},
            {"label": "Ski  –  Mobility", "value": "0000"},
            {"label": "Towed  –  Mobility", "value": "0000"},
            {"label": "Tracked  –  Mobility", "value": "0000"},
            {"label": "Tug Harbor  –  Mobility", "value": "0000"},
            {"label": "Vertical or Short Take-Off and Landing (VTOL/VSTOL)  –  Mobility", "value": "0000"},
            {"label": "Wheeled (Limited Cross Country)  –  Mobility", "value": "0000"},
            {"label": "Wheeled X (Cross Country)  –  Mobility", "value": "0000"}
        ],
        "EchelonMobility": [
            {"label": "Unspecified", "value": "00"},
            {"label": "Team/Crew", "value": "11"},
            {"label": "Squad", "value": "12"},
            {"label": "Section", "value": "13"},
            {"label": "Platoon/Detachment", "value": "14"},
            {"label": "Company/Battery/Troop", "value": "15"},
            {"label": "Battalion/Squadron", "value": "16"},
            {"label": "Regiment/Group", "value": "17"},
            {"label": "Brigade", "value": "18"},
            {"label": "Division", "value": "21"},
            {"label": "Corps/MEF", "value": "22"},
            {"label": "Army", "value": "23"},
            {"label": "Army Group/Front", "value": "24"},
            {"label": "Region/Theater", "value": "25"},
            {"label": "Command", "value": "26"}
        ],
        "HeadquartersTaskforceDummy": [
            {"label": "Unspecified", "value": "0"},
            {"label": "Feint / Dummy", "value": "1"},
            {"label": "Headquarters", "value": "2"},
            {"label": "Feint / Dummy Headquarters", "value": "3"},
            {"label": "Task Force", "value": "4"},
            {"label": "Feint / Dummy Task Force", "value": "5"},
            {"label": "Task Force Headquarters", "value": "6"},
            {"label": "Feint / Dummy Task Force Headquarters", "value": "7"}
        ]
    },
    
    "LAND_CIVILIAN_UNIT_ORGANIZATION": {
        "MainIcon": [
            {"label": "Unspecified", "value": "00"},
            {"label": "Environmental Protection  –  Civilian", "value": "00"},
            {"label": "Government Organization  –  Civilian", "value": "00"},
            {"label": "Individual  –  Civilian", "value": "00"},
            {"label": "Organization or Group  –  Civilian", "value": "00"},
            {"label": "Killing Victim  –  Civilian", "value": "00"},
            {"label": "Killing Victims  –  Civilian", "value": "00"},
            {"label": "Victim of an Attempted Crime  –  Civilian", "value": "00"},
            {"label": "Spy  –  Civilian", "value": "00"},
            {"label": "Composite Loss  –  Civilian", "value": "00"},
            {"label": "Emergency Medical Operation  –  Civilian", "value": "00"}
        ],
        "FirstIconModifier": [
            {"label": "Unspecified", "value": "00"},
            {"label": "Armored  –  Capability", "value": "00"},
            {"label": "Attack or Attack/Strike  –  Capability", "value": "00"},
            {"label": "Ballistic Missile/Ballistic Missile Defense Shooter  –  Capability", "value": "00"},
            {"label": "Bridge/Bridging  –  Capability", "value": "00"},
            {"label": "Cargo  –  Capability", "value": "00"},
            {"label": "Close Protection  –  Capability", "value": "00"},
            {"label": "Combat  –  Capability", "value": "00"},
            {"label": "Command and Control  –  Capability", "value": "00"},
            {"label": "Command Post Node  –  Capability", "value": "00"},
            {"label": "Crowd and Riot Control  –  Capability", "value": "00"},
            {"label": "Cyberspace  –  Capability", "value": "00"},
            {"label": "Directed Energy  –  Capability", "value": "00"},
            {"label": "Electromagnetic  –  Capability", "value": "00"},
            {"label": "Explosive Ordnance Disposal  –  Capability", "value": "00"},
            {"label": "Guided Missile  –  Capability", "value": "00"},
            {"label": "Heavy  –  Capability", "value": "00"},
            {"label": "Intelligence Surveillance Reconnaissance  –  Capability", "value": "00"},
            {"label": "Joint Network Node  –  Capability", "value": "00"},
            {"label": "Light  –  Capability", "value": "00"},
            {"label": "Maintenance  –  Capability", "value": "00"},
            {"label": "Medevac/Medic/Medical  –  Capability", "value": "00"},
            {"label": "Medium  –  Capability", "value": "00"},
            {"label": "Other Guided Missile  –  Capability", "value": "00"},
            {"label": "Petroleum/Petroleum Oil and Lubricants  –  Capability", "value": "00"},
            {"label": "Retransmission Site  –  Capability", "value": "00"},
            {"label": "Search and Rescue  –  Capability", "value": "00"},
            {"label": "Security  –  Capability", "value": "00"},
            {"label": "Sniper  –  Capability", "value": "00"},
            {"label": "Special Operations Forces  –  Capability", "value": "00"},
            {"label": "Special Weapons and Tactics (SWAT)  –  Capability", "value": "00"},
            {"label": "Utility  –  Capability", "value": "00"},
            {"label": "Water  –  Capability", "value": "00"},
            {"label": "Weapon or Weapons  –  Capability", "value": "00"},
            {"label": "Biological  –  CBRN", "value": "00"},
            {"label": "Chemical  –  CBRN", "value": "00"},
            {"label": "Decontamination  –  CBRN", "value": "00"},
            {"label": "Nuclear  –  CBRN", "value": "00"},
            {"label": "Radiological  –  CBRN", "value": "00"},
            {"label": "Other  –  Composite Loss", "value": "00"},
            {"label": "Accident  –  Composite Loss or Incident Qualifier", "value": "00"},
            {"label": "Assassination  –  Crime", "value": "00"},
            {"label": "Execution  –  Crime", "value": "00"},
            {"label": "Hijacker  –  Crime", "value": "00"},
            {"label": "Kidnapping  –  Crime", "value": "00"},
            {"label": "Loot  –  Crime", "value": "00"},
            {"label": "Murder Victims  –  Crime", "value": "00"},
            {"label": "Piracy  –  Crime", "value": "00"},
            {"label": "Rape  –  Crime", "value": "00"},
            {"label": "Antisubmarine Warfare  –  Mission Area", "value": "00"},
            {"label": "Escort  –  Mission Area", "value": "00"},
            {"label": "Mine Countermeasures  –  Mission Area", "value": "00"},
            {"label": "Mine WarfareAPP-06 uses ‘MW’  –  Mission Area", "value": "00"},
            {"label": "Surface Warfare  –  Mission Area", "value": "00"},
            {"label": "Fixed Wing –  Mobility (Not used by USAF)", "value": "00"},
            {"label": "Robotic  –  Mobility", "value": "00"},
            {"label": "Rotary Wing  –  Mobility", "value": "00"},
            {"label": "Tilt-Rotor  –  Mobility", "value": "00"},
            {"label": "Unmanned Aircraft (UA)/ Unmanned Aerial Vehicle (UAV)/ Unmanned Aircraft System (UAS)/ Remote Piloted Vehicle (RPV)  –  Mobility", "value": "00"},
            {"label": "VSTOL/VTOL or Helicopter Equipped  –  Mobility", "value": "00"},
            {"label": "Civilian  –  Organization", "value": "00"},
            {"label": "Displaced Person(s), Refugee(s) and Evacuee(s)  –  Organization", "value": "00"},
            {"label": "Foreign Fighter(s)  –  Organization", "value": "00"},
            {"label": "Gang Member or Gang  –  Organization", "value": "00"},
            {"label": "Government Organization / Government Organization Member  –  Organization", "value": "00"},
            {"label": "Leader or Leadership  –  Organization", "value": "00"},
            {"label": "Nongovernmental Organization Member or Nongovernmental Organization  –  Organization", "value": "00"},
            {"label": "Religious or Religious Organization  –  Organization", "value": "00"},
            {"label": "Speaker  –  Organization", "value": "00"},
            {"label": "Targeted Individual or Organization  –  Organization", "value": "00"},
            {"label": "Terrorist or Terrorist Organization  –  Organization", "value": "00"},
            {"label": "Unwilling/Coerced Recruit  –  Organization", "value": "00"},
            {"label": "Willing Recruit  –  Organization", "value": "00"},
            {"label": "Battalion  –  Support Level", "value": "00"},
            {"label": "Brigade  –  Support Level", "value": "00"},
            {"label": "Command  –  Support Level", "value": "00"},
            {"label": "Company  –  Support Level", "value": "00"},
            {"label": "Platoon/Detachment  –  Support Level", "value": "00"},
            {"label": "Regiment Group  –  Support Level", "value": "00"},
            {"label": "Section  –  Support Level", "value": "00"},
            {"label": "Squad  –  Support Level", "value": "00"},
            {"label": "Team/Crew  –  Support Level", "value": "00"}
        ],
        "SecondIconModifier": [
            {"label": "Unspecified", "value": "00"},
            {"label": "Autonomous Control  –  Capability", "value": "00"},
            {"label": "Close Range  –  Capability", "value": "00"},
            {"label": "Cyberspace  –  Capability", "value": "00"},
            {"label": "Expendable  –  Capability", "value": "00"},
            {"label": "Heavy  –  Capability", "value": "00"},
            {"label": "Light  –  Capability", "value": "00"},
            {"label": "Light and Medium  –  Capability", "value": "00"},
            {"label": "Long Range  –  Capability", "value": "00"},
            {"label": "Medical Bed  –  Capability", "value": "00"},
            {"label": "Medium  –  Capability", "value": "00"},
            {"label": "Medium Range  –  Capability", "value": "00"},
            {"label": "Mountain  –  Capability", "value": "00"},
            {"label": "Multifunctional  –  Capability", "value": "00"},
            {"label": "Railroad/Railway  –  Capability", "value": "00"},
            {"label": "Remotely Piloted  –  Capability", "value": "00"},
            {"label": "Security Force Assistance  –  Capability", "value": "00"},
            {"label": "Short Range  –  Capability", "value": "00"},
            {"label": "Airborne  –  Mobility", "value": "00"},
            {"label": "Bicycle Equipped  –  Mobility", "value": "00"},
            {"label": "Fixed Wing  –  Mobility", "value": "00"},
            {"label": "Robotic  –  Mobility", "value": "00"},
            {"label": "Rotary Wing  –  Mobility", "value": "00"},
            {"label": "Ski  –  Mobility", "value": "00"},
            {"label": "Tracked  –  Mobility", "value": "00"},
            {"label": "Wheeled (Limited Cross Country)  –  Mobility", "value": "00"},
            {"label": "Wheeled X (Cross Country)  –  Mobility", "value": "00"},
            {"label": "Leader or Leadership  –  Organization", "value": "00"}
        ],
        "EchelonMobility": [
            {"label": "Not Applicable", "value": "00"}
        ],
        "HeadquartersTaskforceDummy": [
            {"label": "Unspecified", "value": "00"},
            {"label": "Feint / Dummy", "value": "00"},
            {"label": "Headquarters", "value": "00"},
            {"label": "Feint / Dummy Headquarters", "value": "00"},
            {"label": "Task Force", "value": "00"},
            {"label": "Feint / Dummy Task Force", "value": "00"},
            {"label": "Task Force Headquarters", "value": "00"},
            {"label": "Feint / Dummy Task Force Headquarters", "value": "00"}
        ]
    },
    
    "LAND_EQUIPMENT": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "LAND_INSTALLATIONS": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "CONTROL_MEASURE": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "DISMOUNTED_INDIVIDUALS": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "SEA_SURFACE": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "SEA_SUBSURFACE": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "MINE_WARFARE": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "ACTIVITY_EVENT": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "SIGNALS_INTELLIGENCE_SPACE": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "SIGNALS_INTELLIGENCE_AIR": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "SIGNALS_INTELLIGENCE_LAND": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "SIGNALS_INTELLIGENCE_SURFACE": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "SIGNALS_INTELLIGENCE_SUBSURFACE": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    },
    
    "CYBERSPACE": {
        "MainIcon": [],
        "FirstIconModifier": [],
        "SecondIconModifier": [],
        "EchelonMobility": [],
        "HeadquartersTaskforceDummy": []
    }
}

SYMBOLS = [
    {"id": "AIR",                                 "label": "Air",                                 "value": "01"},
    {"id": "AIR_MISSILE",                         "label": "Air missile",                         "value": "02"},
    {"id": "SPACE",                               "label": "Space",                               "value": "05"},
    {"id": "SPACE_MISSILE",                       "label": "Space missile",                       "value": "06"},
    {"id": "LAND_UNIT",                           "label": "Land unit",                           "value": "10"},
    {"id": "LAND_CIVILIAN_UNIT_ORGANIZATION",     "label": "Land civilian unit/Organization",     "value": "11"},
    {"id": "LAND_EQUIPMENT",                      "label": "Land equipment",                      "value": "15"},
    {"id": "LAND_INSTALLATIONS",                  "label": "Land installations",                  "value": "20"},
    {"id": "CONTROL_MEASURE",                     "label": "Control measure",                     "value": "25"},
    {"id": "DISMOUNTED_INDIVIDUALS",              "label": "Dismounted individuals",              "value": "27"},
    {"id": "SEA_SURFACE",                         "label": "Sea surface",                         "value": "30"},
    {"id": "SEA_SUBSURFACE",                      "label": "Sea subsurface",                      "value": "35"},
    {"id": "MINE_WARFARE",                        "label": "Mine warfare",                        "value": "36"},
    {"id": "ACTIVITY_EVENT",                      "label": "Activity/Event",                      "value": "40"},
    {"id": "SIGNALS_INTELLIGENCE_SPACE",          "label": "Signals Intelligence – Space",        "value": "50"},
    {"id": "SIGNALS_INTELLIGENCE_AIR",            "label": "Signals Intelligence – Air",          "value": "51"},
    {"id": "SIGNALS_INTELLIGENCE_LAND",           "label": "Signals Intelligence – Land",         "value": "52"},
    {"id": "SIGNALS_INTELLIGENCE_SURFACE",        "label": "Signals Intelligence – Surface",      "value": "53"},
    {"id": "SIGNALS_INTELLIGENCE_SUBSURFACE",     "label": "Signals Intelligence – Subsurface",   "value": "54"},
    {"id": "CYBERSPACE",                          "label": "Cyberspace",                          "value": "60"}
]